/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.app,.app-body,.app-content,.app-footer,.app-header{position:relative;margin:0}.app-header{position:relative;background:#28292b;height:300px}.app-header .logo{padding:63px 0}.app-header.single-layout{height:130px}.app-header.single-layout .logo{padding:28px 0}.app-header.single-layout .nav-wrapper{padding:12px 0}@media (max-width:575px){.app-header.single-layout{height:100px}}.app-header .main-nav>.nav-link{color:#676767}.app-header .right-nav .nav-link{text-transform:uppercase}.app-header .search-wrapper{margin-top:12px}.app-body{padding-top:35px;padding-bottom:35px}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL0FwcGxpY2F0aW9ucy9NQU1QL2h0ZG9jcy9iYWNrYW5kLXByb2plY3RzL2ZuaHViL2NsaWVudC9zcmMvYXBwL2FwcC5jb21wb25lbnQuc2Nzcy5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQXBwbGljYXRpb25zL01BTVAvaHRkb2NzL2JhY2thbmQtcHJvamVjdHMvZm5odWIvY2xpZW50L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
